#pragma once

#include <cstdint>
#include <deque>
#include <map>
#include <optional>
#include <ostream>
#include <set>
#include <string>
#include <vector>

#include "dasdl_model.hpp"

// ---------------------------------------------------------------------------
// dasdl_sql.hpp — the database model as a MariaDB schema.
//
// The compiler builds a model of the description (dasdl_model.hpp); this reads
// it and writes the DDL a MariaDB server can hold the same data in, so the
// programs generated by MCP/C74 have something to reach. It is called from
// PROCESS, the FINAL of the GENERAL SECTION, once the parse has succeeded and
// the model has been finalized.
//
// How DMSII maps onto a relational schema
// ---------------------------------------
//   * A **data set** becomes a table. DMSII records have no key of their own —
//     a program reaches a record through a set, or by its address — so every
//     table carries `rsn`, an autoincrementing surrogate standing in for the
//     record serial number DMSII addresses records by.
//   * An **embedded data set** (one declared inside another's record) becomes
//     its own table with `parent_rsn` referencing the owner, deleted with it:
//     an embedded record cannot outlive the record that holds it.
//   * **Groups** are flattened into the owning table, their names joined with
//     `_`. A group is a name for a run of items, not a record of its own.
//   * **OCCURS n** becomes n columns, `name_1 … name_n`, which is the shape the
//     COBOL program is already written against. `DEPENDING ON` names an item of
//     the same record, so the count is a column like any other.
//   * A **set or Access** holds one entry for every record of its data set,
//     which is what an index is, so it becomes one — UNIQUE unless duplicates
//     are allowed. `DATA (…)` items ride along as trailing columns, making it a
//     covering index: the relational form of the KEY-ONLY read the key data
//     option exists for.
//   * A **subset** holds entries for only *some* of the records, and an index
//     cannot leave rows out. It becomes a table of its own — a copy of the key
//     items, a copy of the `DATA (…)` items, and the `rsn` of the record the
//     entry points at — which is the structure DMSII itself builds. Reading
//     whole records through it is a join on `rsn`; a FIND KEY OF never leaves
//     it. An **automatic** subset (one with a WHERE condition) is maintained by
//     the server, through a trigger that adds the entry on a store and one that
//     re-evaluates it on a modify; a deleted record takes its entries with it
//     through the foreign key. A **manual** subset gets no triggers: the
//     program is what puts entries in it, with INSERT and REMOVE, and that is
//     the whole difference between the two.
//   * A **remap** becomes a view: entries renamed, hidden entries left out,
//     virtual items becoming expressions, and a SELECT condition becoming the
//     view's WHERE.
//   * **Global items** — items declared at the top of the description rather
//     than inside a data set — are one record for the whole database, so they
//     become a single-row table.
//   * A **logical database** restricts what a program may see. That is a grant,
//     not a shape, so it is written out as a manifest comment rather than
//     guessed at.
//
// Nothing is dropped in silence. Anything this writer cannot map becomes an
// `-- unsupported:` line in the output, the way the C74 generator emits an
// explicit `_unsupported(...)` call rather than a program that quietly does the
// wrong thing.
//
// Two passes, in that order: `collect()` builds every table and column, then
// nothing adds a column again. The emitting pass hands out `const Column*`
// into those tables, and only a completed table can be pointed into safely.
// ---------------------------------------------------------------------------

namespace dasdl_sql {

using dasdl_model::Database;
using dasdl_model::Node;
using dasdl_model::toUpper;

/** DMSII allows 23 digits unsigned, 22 signed (8600 0213-424, Section 9). A
 *  NUMBER written with no precision at all gets the widest one it could have. */
inline constexpr int DEFAULT_PRECISION = 23;

/** Who keeps the automatic subsets current. DMSII has the database itself do
 *  it, which is what Triggers matches; Runtime leaves that to whatever writes
 *  to the data set tables. */
enum class Maintenance { Triggers, Runtime };

inline std::string toLower(std::string s) {
    for (char& c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}

/** A DASDL name as a SQL identifier: hyphens are word characters in DASDL and
 *  punctuation in SQL, so they become underscores. Everything is quoted on
 *  output anyway, which is what keeps a structure named KEY or ORDER working. */
inline std::string sqlname(const std::string& name) {
    std::string out;
    out.reserve(name.size());
    for (unsigned char c : name)
        out += (std::isalnum(c) || c == '_') ? static_cast<char>(std::tolower(c)) : '_';
    return out;
}

inline std::string quoted(const std::string& name) {
    std::string out = "`";
    for (char c : name) {
        if (c == '`') out += "``";
        else out += c;
    }
    return out + "`";
}

/** A SQL identifier is at most 64 characters. Names here are composed — an
 *  embedded data set takes its owner's name as a prefix, a trigger takes its
 *  subset's — so a long one is shortened by its own digest rather than
 *  truncated onto a name something else already has. FNV-1a rather than a
 *  cryptographic hash: this only has to tell two long names apart. */
inline std::string fit(const std::string& name, size_t limit = 64) {
    if (name.size() <= limit) return name;
    std::uint64_t h = 1469598103934665603ULL;
    for (unsigned char c : name) {
        h ^= c;
        h *= 1099511628211ULL;
    }
    static const char* digits = "0123456789abcdef";
    std::string tag;
    for (int i = 7; i >= 0; --i) tag += digits[(h >> (i * 4)) & 0xF];
    return name.substr(0, limit - 9) + "_" + tag;
}

inline bool isNumericLiteral(const std::string& s, bool allowSign) {
    size_t i = 0;
    if (allowSign && i < s.size() && (s[i] == '+' || s[i] == '-')) ++i;
    size_t digits = 0;
    while (i < s.size() && std::isdigit(static_cast<unsigned char>(s[i]))) { ++i; ++digits; }
    if (!digits) return false;
    if (i == s.size()) return true;
    if (s[i] != '.') return false;
    ++i;
    size_t frac = 0;
    while (i < s.size() && std::isdigit(static_cast<unsigned char>(s[i]))) { ++i; ++frac; }
    return frac > 0 && i == s.size();
}

inline std::string sqlQuote(const std::string& body) {
    std::string out = "'";
    for (char c : body) {
        if (c == '\'') out += "''";
        else out += c;
    }
    return out + "'";
}

/** A DASDL item value as a SQL literal. */
inline std::string literal(const std::string& text) {
    if (text.size() >= 2 && text.front() == '"' && text.back() == '"')
        return sqlQuote(text.substr(1, text.size() - 2));
    if (isNumericLiteral(text, true)) return text;
    if (text == "TRUE" || text == "FALSE") return text;
    if (text == "BLANKS") return "''";
    if (text == "HIGH-VALUE" || text == "LOW-VALUE") return "NULL";
    return sqlQuote(text);
}

inline std::string join(const std::vector<std::string>& parts, const std::string& sep) {
    std::string out;
    for (size_t i = 0; i < parts.size(); ++i) {
        if (i) out += sep;
        out += parts[i];
    }
    return out;
}

// ---------------------------------------------------------------------------

/** One column of a generated table, and the DASDL item it came from. */
struct Column {
    std::string name;                 // SQL identifier
    std::string sqlType;
    const Node* item = nullptr;       // the model node
    std::vector<std::string> path;    // DASDL names from the record down, upper case

    const std::string& dasdlName() const { return path.back(); }
};

struct Table {
    std::string name;                 // SQL identifier
    const Node* node = nullptr;       // the data set node; null for the globals table
    const Table* parent = nullptr;    // owning Table for an embedded data set
    std::vector<Column> columns;
    std::vector<std::string> notes;   // `-- unsupported:` lines to print with it
    // The structures declared beside the items of this record — embedded data
    // sets, and the sets and remaps that reach them. A remap carries them over
    // by name, and they are ways in rather than columns.
    std::set<std::string> structures;

    /** The columns a DASDL name stands for. A group name stands for all of its
     *  leaves, in record order, which is what a key over a group means. */
    std::vector<const Column*> find(const std::string& dasdlName) const {
        const std::string want = toUpper(dasdlName);
        std::vector<const Column*> hits;
        for (const Column& c : columns)
            if (c.dasdlName() == want) hits.push_back(&c);
        if (!hits.empty()) return hits;
        for (const Column& c : columns) {
            for (size_t i = 0; i + 1 < c.path.size(); ++i)
                if (c.path[i] == want) { hits.push_back(&c); break; }
        }
        return hits;
    }
};

// ---------------------------------------------------------------------------

class SchemaWriter {
public:
    explicit SchemaWriter(const Database& db, Maintenance maintenance = Maintenance::Triggers)
        : db_(db), maintenance_(maintenance) {}

    void write(std::ostream& os) {
        collect();
        emitHeader();
        emitGlobals();
        for (Table* t : dataSets_) emitTable(*t);
        emitAccessPaths();
        emitViews();
        emitLogicalDatabases();
        for (const std::string& line : out_) os << line << '\n';
    }

    int unsupportedCount() const { return unsupported_; }

private:
    // ---- output helpers ---------------------------------------------------

    void emit(const std::string& text = {}) { out_.push_back(text); }

    void unsupported(const std::string& what) {
        ++unsupported_;
        emit("-- unsupported: " + what);
    }

    /** Claim a schema-wide name. False when something already has it. */
    bool issue(const std::string& name, const std::string& what) {
        auto it = issued_.find(name);
        if (it != issued_.end()) {
            unsupported(what + " wants the name " + name + ", which " +
                        it->second + " already has");
            return false;
        }
        issued_[name] = what;
        return true;
    }

    // ---- pass 1: tables ---------------------------------------------------

    void collect() {
        for (const auto& node : db_.nodes) {
            if (node->kind == "dataset") collectDataSet(*node, nullptr);
            else if (node->kind == "item") globals_.push_back(node.get());
        }
        if (globals_.empty()) return;
        tables_.push_back(Table{});
        Table& t = tables_.back();
        t.name = "dmsii_globals";
        for (const Node* item : globals_) addColumns(t, *item, {});
        if (!t.columns.empty()) globalsTable_ = &t;
    }

    void collectDataSet(const Node& node, Table* owner) {
        tables_.push_back(Table{});
        Table& table = tables_.back();
        table.name = owner ? owner->name + "_" + sqlname(node.name) : sqlname(node.name);
        table.node = &node;
        table.parent = owner;
        for (const auto& item : node.children) {
            if (item->kind == "dataset" || item->kind == "set" ||
                item->kind == "subset" || item->kind == "access" ||
                item->kind == "remap")
                table.structures.insert(toUpper(item->name));
        }
        dataSets_.push_back(&table);
        byNode_[&node] = &table;
        byName_.emplace(node.name, &table);
        for (const auto& item : node.children) {
            if (item->kind == "dataset") collectDataSet(*item, &table);
            else addColumns(table, *item, {});
        }
    }

    /** Turn one record entry into columns of `table`. Groups recurse, OCCURS
     *  repeats, and everything that is not data in the record — a set declared
     *  beside the items, a remap, a virtual item — is left for the passes that
     *  know what to do with it. */
    void addColumns(Table& table, const Node& item, const std::vector<std::string>& path) {
        const std::string& kind = item.kind;
        if (kind == "set" || kind == "subset" || kind == "access" ||
            kind == "remap" || kind == "format" || kind == "filler")
            return;
        if (item.isVirtual) return;              // belongs to the remap's view
        if (kind == "carried" && item.type.empty()) return;  // a name repeated in a remap

        std::vector<std::string> here = path;
        here.push_back(toUpper(item.name));
        if (item.occurs) {
            for (int i = 1; i <= item.occurs; ++i)
                addOne(table, item, here, "_" + std::to_string(i));
        } else {
            addOne(table, item, here, {});
        }
    }

    void addOne(Table& table, const Node& item,
                const std::vector<std::string>& path, const std::string& suffix) {
        if (item.type == "group") {
            const size_t before = table.columns.size();
            for (const auto& child : item.children) addColumns(table, *child, path);
            // An OCCURS group repeats every leaf under it, so every leaf this
            // repetition added carries the suffix that tells the copies apart.
            if (!suffix.empty())
                for (size_t i = before; i < table.columns.size(); ++i)
                    table.columns[i].name += suffix;
            return;
        }
        if (item.type == "field" && !item.children.empty()) {
            for (const auto& bit : item.children) {
                std::vector<std::string> bitPath = path;
                bitPath.push_back(toUpper(bit->name));
                Column col;
                col.name = sqlname(join(names(path, bit->name), "_")) + suffix;
                col.sqlType = "BOOLEAN";
                col.item = bit.get();
                col.path = bitPath;
                table.columns.push_back(std::move(col));
            }
            return;
        }
        std::string type;
        if (!sqlType(item, table, type)) return;
        Column col;
        col.name = sqlname(join(path, "_")) + suffix;
        col.sqlType = std::move(type);
        col.item = &item;
        col.path = path;
        table.columns.push_back(std::move(col));
    }

    static std::vector<std::string> names(const std::vector<std::string>& path,
                                          const std::string& tail) {
        std::vector<std::string> out = path;
        out.push_back(tail);
        return out;
    }

    bool sqlType(const Node& item, Table& table, std::string& out) {
        const std::string& type = item.type;
        if (type == "alpha") {
            const int n = item.size ? item.size : 1;
            // CHAR tops out at 255; ALPHA is blank-padded, which is CHAR's own
            // rule, so the wider ones become VARCHAR and keep their length.
            out = (n <= 255 ? "CHAR(" : "VARCHAR(") + std::to_string(n) + ")";
            return true;
        }
        if (type == "number") {
            const int precision = item.size ? item.size : DEFAULT_PRECISION;
            out = "DECIMAL(" + std::to_string(precision) + "," +
                  std::to_string(item.scale) + ")" + (item.isSigned ? "" : " UNSIGNED");
            return true;
        }
        if (type == "real") {
            // One MCP word of single-precision floating point. DOUBLE is the
            // narrowest SQL type that holds it without rounding it away.
            out = "DOUBLE";
            return true;
        }
        if (type == "boolean") { out = "BOOLEAN"; return true; }
        if (type == "field") {
            const int bits = item.size ? item.size : 1;
            out = bits <= 64 ? "BIT(" + std::to_string(bits) + ")"
                             : "VARBINARY(" + std::to_string((bits + 7) / 8) + ")";
            return true;
        }
        if (type == "population" || type == "count") { out = "BIGINT UNSIGNED"; return true; }
        table.notes.push_back("item " + item.name +
                              ": no type in the description, no column made");
        return false;
    }

    // ---- pass 2: emit -----------------------------------------------------

    void emitHeader() {
        emit("-- MariaDB schema for the Enterprise Database Server database " + db_.name);
        emit("-- Compiled from " + db_.source + " by DASDL.");
        emit("--");
        emit("-- Every table carries `rsn`: DMSII addresses a record by its");
        emit("-- record serial number, and a relational row needs a key of");
        emit("-- its own for the sets that reach it to point at something.");
        emit("--");
        emit("-- A set is an index over its data set; a subset is a table of");
        emit("-- its own, because it holds entries for only some of the");
        emit("-- records and an index cannot leave rows out. Reading whole");
        emit("-- records through a subset is a join on `rsn`; reading only");
        emit("-- its keys and DATA items — a FIND KEY OF — never leaves it.");
        emit();
        const std::string name = sqlname(db_.name.empty() ? "dmsii" : db_.name);
        emit("CREATE DATABASE IF NOT EXISTS " + quoted(name) +
             " DEFAULT CHARACTER SET utf8mb4;");
        emit("USE " + quoted(name) + ";");
        emit();
    }

    void emitGlobals() {
        if (!globalsTable_) return;
        emit("-- The database's global items: one record for the whole");
        emit("-- database, so one row, held down by a fixed key.");
        issue("dmsii_globals", "the global items");
        emit("CREATE TABLE IF NOT EXISTS `dmsii_globals` (");
        std::vector<std::string> lines{"  `rsn` TINYINT UNSIGNED NOT NULL DEFAULT 1"};
        for (const Column& col : globalsTable_->columns)
            lines.push_back("  " + columnLine(col));
        lines.push_back("  PRIMARY KEY (`rsn`)");
        lines.push_back("  CHECK (`rsn` = 1)");
        emit(join(lines, ",\n"));
        emit(") ENGINE=InnoDB;");
        for (const std::string& note : globalsTable_->notes) unsupported(note);
        emit();
    }

    std::string columnLine(const Column& col) {
        std::vector<std::string> parts{quoted(col.name), col.sqlType};
        const Node& item = *col.item;
        if (item.required) parts.push_back("NOT NULL");
        if (item.hasInitial) {
            const std::string value = literal(item.initialValue);
            if (value != "NULL") parts.push_back("DEFAULT " + value);
        }
        std::vector<std::string> comment;
        // DMSII spells its null as a value in the item's own domain; SQL has a
        // null of its own, so the declared one is recorded and the column is
        // left nullable.
        if (item.hasNull) comment.push_back("DMSII NULL " + item.nullValue);
        if (item.readOnly) comment.push_back("READONLY");
        if (!item.dependingOn.empty())
            comment.push_back("OCCURS DEPENDING ON " + item.dependingOn);
        if (!comment.empty()) parts.push_back("COMMENT " + sqlQuote(join(comment, "; ")));
        return join(parts, " ");
    }

    void emitTable(const Table& table) {
        const Node& node = *table.node;
        emit("-- " + node.name +
             (node.datasetKind.empty() ? " (data set)"
                                       : " (" + toLower(node.datasetKind) + " data set)") +
             (table.parent ? ", embedded in " + table.parent->node->name : ""));
        if (!issue(table.name, "data set " + node.name)) return;
        emit("CREATE TABLE IF NOT EXISTS " + quoted(table.name) + " (");
        std::vector<std::string> lines{"  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT"};
        if (table.parent) lines.push_back("  `parent_rsn` BIGINT UNSIGNED NOT NULL");
        for (const Column& col : table.columns) lines.push_back("  " + columnLine(col));
        lines.push_back("  PRIMARY KEY (`rsn`)");
        if (table.parent) {
            lines.push_back("  KEY `" + table.name + "_parent` (`parent_rsn`)");
            lines.push_back("  CONSTRAINT " + quoted(table.name + "_owner") +
                            " FOREIGN KEY (`parent_rsn`) REFERENCES " +
                            quoted(table.parent->name) + " (`rsn`) ON DELETE CASCADE");
        }
        emit(join(lines, ",\n"));
        emit(") ENGINE=InnoDB;");
        for (const std::string& note : table.notes) unsupported(note);
        emit();
    }

    // ---- walking the description ------------------------------------------

    /** Every structure in the description, paired with the table it was
     *  declared inside — a set declared in a record is over the data set
     *  embedded beside it. */
    struct Reached {
        const Node* node;
        const Table* owner;
    };

    std::vector<Reached> eachStructure() const {
        std::vector<Reached> out;
        walk(db_.nodes, nullptr, out);
        return out;
    }

    void walk(const std::vector<dasdl_model::NodePtr>& nodes, const Table* owner,
              std::vector<Reached>& out) const {
        for (const auto& child : nodes) {
            out.push_back(Reached{child.get(), owner});
            if (child->kind == "dataset") {
                auto it = byNode_.find(child.get());
                walk(child->children, it == byNode_.end() ? nullptr : it->second, out);
            } else if (child->kind == "remap" || child->kind == "logical-database") {
                continue;
            } else {
                walk(child->children, owner, out);
            }
        }
    }

    const Table* targetTable(const Node& node, const Table* owner) const {
        if (node.target.empty()) return nullptr;
        if (owner && owner->node) {
            for (const auto& item : owner->node->children) {
                if (item->kind == "dataset" && item->name == node.target) {
                    auto it = byNode_.find(item.get());
                    return it == byNode_.end() ? nullptr : it->second;
                }
            }
        }
        auto it = byName_.find(node.target);
        return it == byName_.end() ? nullptr : it->second;
    }

    // ---- access paths: sets, subsets and Accesses --------------------------
    //
    // A **set** holds one entry for every record of its data set, so an index
    // over the table is exactly what it is: the server maintains it, and it is
    // never out of step with the rows.
    //
    // A **subset** holds entries for only *some* of the records, and an index
    // cannot leave rows out. It becomes a table of its own — one row per entry,
    // holding a copy of the key items, a copy of the DATA items, and the `rsn`
    // of the record the entry points at. That is the structure DMSII actually
    // builds, and it is what makes a KEY-ONLY read one lookup in a small table
    // instead of a filtered scan of a large one.
    //
    // Which of the two a declaration is comes from the where condition rather
    // than from the word SET or SUBSET (Section 11): "a subset that includes a
    // where condition is called an automatic subset", one without it is manual
    // and the program maintains it with INSERT and REMOVE.

    static bool isSubset(const Node& node) {
        return node.kind == "subset" || !node.whereText.empty();
    }

    /** Whether two entries may carry the same key — as written, or as the
     *  manual has it when nothing is written. A set defaults to NO DUPLICATES,
     *  an automatic subset to DUPLICATES, a manual subset to NO DUPLICATES:
     *  Section 11 spells out all three, and says in as many words that "SETS
     *  and SUBSETS have different defaults". */
    static bool duplicatesAllowed(const Node& node) {
        if (node.duplicatesSeen) return node.duplicatesAllowed;
        return !node.whereText.empty();
    }

    /** What emitSubset built, and what its maintenance will need. */
    struct BuiltSubset {
        const Node* node = nullptr;
        const Table* table = nullptr;
        std::string sub;
        std::vector<std::pair<const Column*, bool>> keys;
        std::vector<const Column*> data;
        std::string ownerCol;
        const Table* ownerTable = nullptr;
    };

    void emitAccessPaths() {
        std::vector<Reached> indexes, subsets;
        for (const Reached& r : eachStructure()) {
            const std::string& kind = r.node->kind;
            if (kind != "set" && kind != "subset" && kind != "access") continue;
            (isSubset(*r.node) ? subsets : indexes).push_back(r);
        }

        if (!indexes.empty()) {
            emit("-- Sets and Accesses: an entry for every record of the data");
            emit("-- set, which is what an index is.");
            for (const Reached& r : indexes) emitIndex(*r.node, r.owner);
            emit();
        }
        if (subsets.empty()) return;
        emit("-- Subsets: an entry for only some of the records, which an");
        emit("-- index cannot be. Each is a table of its own, holding the");
        emit("-- key items, the DATA items and the `rsn` of the record the");
        emit("-- entry points at — so a FIND KEY OF is one lookup here and");
        emit("-- never reaches the data set, which is what the key data");
        emit("-- option exists for.");
        std::vector<BuiltSubset> maintained;
        for (const Reached& r : subsets) {
            BuiltSubset built;
            if (emitSubset(*r.node, r.owner, built)) maintained.push_back(built);
        }
        emit();
        emitSubsetMaintenance(maintained);
    }

    // ---- the columns a key list or a DATA list names ----------------------

    /** A structure declared inside a record exists once per record of that data
     *  set, so its entries have to say which one they belong to.
     *
     *  Two shapes reach here. Usually the structure sits beside the embedded
     *  data set it is over — Section 11 requires exactly that of an automatic
     *  one — and then the owner is already on the target row as `parent_rsn`,
     *  because the target is the owner's own embedded data set. Otherwise the
     *  structure is over a data set somewhere else, which is the manual subset
     *  standing in for a link, and the owner is a column of its own.
     *
     *  Leaves both empty at the top level, where there is one of the structure
     *  for the whole database. */
    static void ownerColumn(const Table& table, const Table* owner,
                            std::string& column, const Table*& reference) {
        column.clear();
        reference = nullptr;
        if (!owner) return;
        if (table.parent == owner) { column = "`parent_rsn`"; return; }
        column = "`owner_rsn`";
        reference = owner;
    }

    /** (column, descending) for each key item, in order. False when a name is
     *  not an item of the record — a key over something the data set does not
     *  declare is not something to guess at. */
    bool keyColumns(const Node& node, const Table& table,
                    std::vector<std::pair<const Column*, bool>>& out) {
        for (const dasdl_model::KeyRef& key : node.keys) {
            std::vector<const Column*> hits = table.find(key.name);
            if (hits.empty()) {
                unsupported(node.kind + " " + node.name + ": key " + key.name +
                            " is not an item of " + table.node->name);
                return false;
            }
            for (const Column* col : hits)
                out.emplace_back(col, key.order == "DESCENDING");
        }
        return true;
    }

    /** The columns a DATA(...) list names. A missing one costs the entry that
     *  copy, not the whole structure, so it is reported and skipped. */
    std::vector<const Column*> dataColumns(const Node& node, const Table& table) {
        std::vector<const Column*> out;
        for (const dasdl_model::KeyRef& item : node.dataItems) {
            std::vector<const Column*> hits = table.find(item.name);
            if (hits.empty()) {
                unsupported(node.kind + " " + node.name + ": DATA item " +
                            item.name + " is not an item of " + table.node->name);
                continue;
            }
            out.insert(out.end(), hits.begin(), hits.end());
        }
        return out;
    }

    // ---- sets and Accesses: an index ---------------------------------------

    void emitIndex(const Node& node, const Table* owner) {
        const Table* table = targetTable(node, owner);
        if (!table) {
            unsupported(node.kind + " " + node.name + ": " +
                        (node.target.empty() ? "?" : node.target) +
                        " is not a data set declared here");
            return;
        }
        if (node.setType == "BIT VECTOR" || node.setType == "LIST" ||
            node.setType == "UNORDERED LIST") {
            // These refer to a record by its place in the data set rather than
            // by a key, so there is nothing for an index to be over.
            unsupported(node.kind + " " + node.name + ": " + toLower(node.setType) +
                        ", no key to index " + table->name + " by");
            return;
        }
        std::vector<std::pair<const Column*, bool>> keys;
        if (!keyColumns(node, *table, keys)) return;
        if (keys.empty()) {
            unsupported(node.kind + " " + node.name + ": no key items");
            return;
        }
        const std::string index = sqlname(node.name);
        const bool unique = !duplicatesAllowed(node);
        // DESC is accepted by every MariaDB and honoured from 10.8; on an older
        // server the index is simply read backwards.
        std::vector<std::string> columns;
        for (const auto& k : keys)
            columns.push_back(quoted(k.first->name) + (k.second ? " DESC" : ""));
        std::string ownerCol;
        const Table* ownerTable = nullptr;
        ownerColumn(*table, owner, ownerCol, ownerTable);
        if (ownerTable) {
            // The set is one per record of the data set it was declared in, but
            // it is over a data set somewhere else, so the rows it would index
            // carry nothing saying which owner they belong to. An index cannot
            // invent that column.
            unsupported(node.kind + " " + node.name + ": declared inside " +
                        owner->node->name + " but over " + table->node->name +
                        ", so its entries are per owning record and an index over " +
                        table->name + " is not");
            return;
        }
        if (!ownerCol.empty()) {
            // A key of an embedded data set is unique within its owner, not
            // across the table every owner's records share.
            columns.insert(columns.begin(), ownerCol);
        }
        const std::string keyRef = join(columns, ", ");
        std::vector<const Column*> data = dataColumns(node, *table);
        std::set<std::string> seen;
        for (const auto& k : keys) seen.insert(k.first->name);
        std::vector<std::string> extra;
        for (const Column* col : data)
            if (!seen.count(col->name)) extra.push_back(quoted(col->name));
        if (extra.empty()) {
            emit("CREATE " + std::string(unique ? "UNIQUE " : "") + "INDEX " +
                 quoted(index) + " ON " + quoted(table->name) + " (" + keyRef + ");");
            return;
        }
        // The key data option copies items into the entry so a KEY-ONLY read
        // never touches the data set. Trailing columns on the index are the
        // same bargain — a covering index. They cannot ride on a UNIQUE one,
        // which would then be unique over key and data together rather than
        // over the key, so that case gets a second index instead.
        const std::string covering = keyRef + ", " + join(extra, ", ");
        if (unique) {
            emit("CREATE UNIQUE INDEX " + quoted(index) + " ON " +
                 quoted(table->name) + " (" + keyRef + ");");
            emit("CREATE INDEX " + quoted(fit(index + "_keydata")) + " ON " +
                 quoted(table->name) + " (" + covering + ");");
        } else {
            emit("CREATE INDEX " + quoted(index) + " ON " +
                 quoted(table->name) + " (" + covering + ");");
        }
    }

    // ---- subsets: a table -------------------------------------------------

    bool emitSubset(const Node& node, const Table* owner, BuiltSubset& built) {
        const Table* table = targetTable(node, owner);
        if (!table) {
            unsupported(node.kind + " " + node.name + ": " +
                        (node.target.empty() ? "?" : node.target) +
                        " is not a data set declared here");
            return false;
        }
        std::vector<std::pair<const Column*, bool>> keys;
        if (!keyColumns(node, *table, keys)) return false;
        std::vector<const Column*> data = dataColumns(node, *table);
        const std::string sub = sqlname(node.name);
        if (!issue(sub, node.kind + " " + node.name)) return false;

        const bool automatic = !node.whereText.empty();
        emit("-- " + node.name + ": " + (automatic ? "automatic" : "manual") +
             " subset of " + table->node->name +
             (node.setType.empty() ? "" : ", " + toLower(node.setType)));
        if (owner)
            emit("--   one per record of " + owner->node->name +
                 ", which is where it is declared");
        if (!node.duplicatesOption.empty()) {
            // FIRST and LAST say which end of a run of duplicates a find lands
            // on, and KEYCHANGEOK says a modify may move a record to a new key.
            // Both are about how the entries are traversed rather than what is
            // in them, so they are recorded and not enforced.
            emit("--   DUPLICATES " + node.duplicatesOption);
        }
        if (automatic) emit("--   holds the records where " + node.whereText);
        else emit("--   the program decides what is in it: INSERT and REMOVE, "
                  "not the server");

        std::string ownerCol;
        const Table* ownerTable = nullptr;
        ownerColumn(*table, owner, ownerCol, ownerTable);
        std::vector<std::string> lines;
        std::set<std::string> seen;
        if (!ownerCol.empty()) {
            // The subset is one per record of the data set it was declared in,
            // so the owner leads its key: two owners may hold entries under the
            // same key without colliding.
            lines.push_back("  " + ownerCol + " BIGINT UNSIGNED NOT NULL");
        }
        for (const auto& k : keys) {
            // Key items are automatically required for an automatic subset
            // (Section 11), and a key column of a primary key is NOT NULL
            // whatever the description said.
            lines.push_back("  " + quoted(k.first->name) + " " + k.first->sqlType +
                            " NOT NULL");
            seen.insert(k.first->name);
        }
        for (const Column* col : data) {
            if (seen.count(col->name)) continue;
            lines.push_back("  " + quoted(col->name) + " " + col->sqlType);
            seen.insert(col->name);
        }
        lines.push_back("  `rsn` BIGINT UNSIGNED NOT NULL");

        if (keys.empty()) {
            // A bit vector or an unordered list keeps no key: the entry is the
            // membership, and the record it points at is all of it.
            lines.push_back("  PRIMARY KEY (`rsn`)");
        } else {
            std::vector<std::string> keyParts;
            if (!ownerCol.empty()) keyParts.push_back(ownerCol);
            for (const auto& k : keys)
                keyParts.push_back(quoted(k.first->name) + (k.second ? " DESC" : ""));
            const std::string keyRef = join(keyParts, ", ");
            if (!duplicatesAllowed(node)) {
                lines.push_back("  PRIMARY KEY (" + keyRef + ")");
            } else {
                // Duplicates are allowed, so the key alone does not identify an
                // entry; the record it points at finishes the job, and orders
                // the duplicates by the order they arrived in.
                lines.push_back("  PRIMARY KEY (" + keyRef + ", `rsn`)");
            }
            lines.push_back(std::string("  ") + (automatic ? "UNIQUE KEY" : "KEY") +
                            " " + quoted(fit(sub + "_record")) + " (`rsn`)");
        }
        if (ownerTable) {
            lines.push_back("  CONSTRAINT " + quoted(fit(sub + "_belongs_to")) +
                            " FOREIGN KEY (" + ownerCol + ") REFERENCES " +
                            quoted(ownerTable->name) + " (`rsn`) ON DELETE CASCADE");
        }
        lines.push_back("  CONSTRAINT " + quoted(fit(sub + "_points_at")) +
                        " FOREIGN KEY (`rsn`) REFERENCES " + quoted(table->name) +
                        " (`rsn`) ON DELETE CASCADE");
        emit("CREATE TABLE IF NOT EXISTS " + quoted(sub) + " (");
        emit(join(lines, ",\n"));
        emit(") ENGINE=InnoDB;");
        if (!automatic) {
            // DMSII lets a record be deleted while a manual subset still points
            // at it, and says finds through that entry are unpredictable
            // afterwards. A dangling row is worse here than a missing one, so
            // the reference cascades — a deliberate difference, not an
            // oversight.
            emit("--   a deleted record takes its entry with it; DMSII leaves "
                 "the entry behind");
        }
        built = BuiltSubset{&node, table, sub, keys, data, ownerCol, ownerTable};
        return true;
    }

    /** Automatic subsets are maintained by the system in DMSII, so they are
     *  maintained by the server here: a trigger adds the entry when a stored
     *  record satisfies the condition, and another re-evaluates it on every
     *  modify — which is also what keeps the copied DATA items current. A
     *  deleted record takes its entries with it through the foreign key, so
     *  there is no third trigger.
     *
     *  Manual subsets get none of this: the program is what puts entries in
     *  them, and that is the whole difference between the two. */
    void emitSubsetMaintenance(const std::vector<BuiltSubset>& subsets) {
        std::vector<const BuiltSubset*> automatic;
        for (const BuiltSubset& s : subsets)
            if (!s.node->whereText.empty()) automatic.push_back(&s);
        if (automatic.empty()) return;
        if (maintenance_ != Maintenance::Triggers) {
            emit("-- Automatic subsets are maintained by the runtime, not by the server:");
            emit("-- no triggers were generated (--maintain=runtime). Whatever writes to");
            emit("-- the data set tables owes each subset its entry.");
            emit();
            return;
        }
        emit("-- Keeping the automatic subsets current. DELIMITER is a");
        emit("-- directive of the mariadb client, not a statement: it is");
        emit("-- what lets a trigger body hold more than one statement.");
        emit("DELIMITER $$");
        for (const BuiltSubset* s : automatic) emitTriggers(*s);
        emit("DELIMITER ;");
        emit();
    }

    void emitTriggers(const BuiltSubset& s) {
        const Node& node = *s.node;
        if (s.ownerTable) {
            // Section 11: an automatic subset has to be declared at the same
            // level as the data set it refers to. This one is not, so a stored
            // record does not say which owner's subset it belongs in.
            unsupported(node.kind + " " + node.name + ": automatic, but declared "
                        "away from the data set it is over, so nothing can tell "
                        "which record owns an entry");
            return;
        }
        std::optional<std::string> condition = translate(node.whereText, s.table, "NEW.");
        if (!condition) {
            unsupported(node.kind + " " + node.name + ": WHERE " + node.whereText +
                        " does not translate, so nothing maintains " + s.sub);
            return;
        }
        std::vector<const Column*> columns;
        std::set<std::string> seen;
        for (const auto& k : s.keys) {
            columns.push_back(k.first);
            seen.insert(k.first->name);
        }
        for (const Column* col : s.data)
            if (seen.insert(col->name).second) columns.push_back(col);
        std::vector<std::string> names, values;
        for (const Column* col : columns) {
            names.push_back(quoted(col->name));
            values.push_back("NEW." + quoted(col->name));
        }
        std::string nameList = join(names, ", ") + (names.empty() ? "" : ", ") + "`rsn`";
        std::string valueList = join(values, ", ") + (values.empty() ? "" : ", ") + "NEW.`rsn`";
        if (!s.ownerCol.empty()) {
            nameList = s.ownerCol + ", " + nameList;
            valueList = "NEW." + s.ownerCol + ", " + valueList;
        }
        const std::string insert = "INSERT INTO " + quoted(s.sub) + " (" + nameList +
                                   ") VALUES (" + valueList + ");";

        emit("CREATE TRIGGER " + quoted(fit(s.sub + "_on_store")) + " AFTER INSERT ON " +
             quoted(s.table->name) + " FOR EACH ROW");
        emit("BEGIN");
        emit("  IF " + *condition + " THEN");
        emit("    " + insert);
        emit("  END IF;");
        emit("END$$");
        // A modify can move a record into the subset, out of it, or leave it
        // there with different key or DATA items. Dropping the entry and
        // rebuilding it covers all three without asking which one happened.
        emit("CREATE TRIGGER " + quoted(fit(s.sub + "_on_modify")) + " AFTER UPDATE ON " +
             quoted(s.table->name) + " FOR EACH ROW");
        emit("BEGIN");
        emit("  DELETE FROM " + quoted(s.sub) + " WHERE `rsn` = OLD.`rsn`;");
        emit("  IF " + *condition + " THEN");
        emit("    " + insert);
        emit("  END IF;");
        emit("END$$");
    }

    // ---- conditions and expressions ---------------------------------------

    /** The relational operators of a DASDL condition, in SQL. */
    static const std::map<std::string, std::string>& relations() {
        static const std::map<std::string, std::string> table{
            {"EQL", "="}, {"NEQ", "<>"}, {"LSS", "<"}, {"LEQ", "<="},
            {"GTR", ">"}, {"GEQ", ">="}, {"=", "="}, {"<", "<"}, {">", ">"},
            {"^", "NOT"}};
        return table;
    }

    /** A DASDL condition as a SQL one. The model keeps the run of tokens that
     *  spelled it, so this is a word-for-word translation: names become
     *  columns, DASDL's mnemonic relations become the symbols SQL spells them
     *  with, and anything naming something that is not a column of the table
     *  gives up rather than guessing. */
    std::optional<std::string> translate(const std::string& text, const Table* table,
                                         const std::string& prefix = {}) const {
        std::vector<std::string> out;
        for (const std::string& token : tokenize(text)) {
            if (token == "AND" || token == "OR" || token == "NOT" || token == "(" ||
                token == ")" || token == "+" || token == "-" || token == "*" ||
                token == "/" || token == "TRUE" || token == "FALSE") {
                out.push_back(token);
                continue;
            }
            auto rel = relations().find(token);
            if (rel != relations().end()) { out.push_back(rel->second); continue; }
            if (token.size() >= 2 && token.front() == '"') {
                out.push_back(sqlQuote(token.substr(1, token.size() - 2)));
                continue;
            }
            if (isNumericLiteral(token, false)) { out.push_back(token); continue; }
            std::vector<const Column*> hits = table ? table->find(token)
                                                    : std::vector<const Column*>{};
            if (hits.size() != 1) return std::nullopt;
            out.push_back(prefix + quoted(hits[0]->name));
        }
        if (out.empty()) return std::nullopt;
        return join(out, " ");
    }

    /** A quoted string, a word, a number, or any other single character. */
    static std::vector<std::string> tokenize(const std::string& text) {
        std::vector<std::string> out;
        size_t i = 0;
        while (i < text.size()) {
            const unsigned char c = static_cast<unsigned char>(text[i]);
            if (std::isspace(c)) { ++i; continue; }
            if (c == '"') {
                const size_t close = text.find('"', i + 1);
                if (close == std::string::npos) { out.push_back(text.substr(i)); break; }
                out.push_back(text.substr(i, close - i + 1));
                i = close + 1;
            } else if (std::isalpha(c)) {
                size_t j = i;
                while (j < text.size() &&
                       (std::isalnum(static_cast<unsigned char>(text[j])) || text[j] == '-'))
                    ++j;
                out.push_back(text.substr(i, j - i));
                i = j;
            } else if (std::isdigit(c)) {
                size_t j = i;
                while (j < text.size() && std::isdigit(static_cast<unsigned char>(text[j]))) ++j;
                if (j < text.size() && text[j] == '.' && j + 1 < text.size() &&
                    std::isdigit(static_cast<unsigned char>(text[j + 1]))) {
                    ++j;
                    while (j < text.size() && std::isdigit(static_cast<unsigned char>(text[j]))) ++j;
                }
                out.push_back(text.substr(i, j - i));
                i = j;
            } else {
                out.push_back(std::string(1, text[i]));
                ++i;
            }
        }
        return out;
    }

    // ---- remaps -----------------------------------------------------------

    void emitViews() {
        std::vector<Reached> remaps;
        for (const Reached& r : eachStructure())
            if (r.node->kind == "remap") remaps.push_back(r);
        if (remaps.empty()) return;
        emit("-- Remaps: a second description of a record, which is a view");
        emit("-- of the table the record is in.");
        for (const Reached& r : remaps) emitView(*r.node, r.owner);
        emit();
    }

    void emitView(const Node& node, const Table* owner) {
        const Table* table = nullptr;
        std::string base;
        if (node.globalData) {
            table = globalsTable_;
            base = "dmsii_globals";
            if (!table) {
                unsupported("remap " + node.name + ": redescribes global items, "
                            "and this description declares none");
                return;
            }
        } else {
            table = targetTable(node, owner);
            if (!table) {
                unsupported("remap " + node.name + ": " +
                            (node.target.empty() ? "?" : node.target) +
                            " is not a data set declared here");
                return;
            }
            base = table->name;
        }

        std::vector<std::string> select;
        for (const auto& entry : node.children) {
            std::vector<std::string> part = viewColumns(*entry, *table, node.name);
            select.insert(select.end(), part.begin(), part.end());
        }
        if (select.empty()) {
            unsupported("remap " + node.name + ": nothing left to select");
            return;
        }
        if (!issue(sqlname(node.name), "remap " + node.name)) return;
        emit("CREATE OR REPLACE VIEW " + quoted(sqlname(node.name)) + " AS");
        emit("  SELECT `rsn`,");
        std::vector<std::string> indented;
        for (const std::string& s : select) indented.push_back("         " + s);
        emit(join(indented, ",\n"));
        emit("    FROM " + dasdl_sql::quoted(base));
        if (!node.selectText.empty()) {
            std::optional<std::string> where = translate(node.selectText, table);
            if (!where)
                unsupported("remap " + node.name + ": SELECT " + node.selectText +
                            " does not translate");
            else
                emit("   WHERE " + *where);
        }
        emit("  ;");
        if (!node.verifyText.empty()) {
            // VERIFY says what may be stored, not what is returned: a view
            // cannot carry it, and WITH CHECK OPTION would apply the SELECT
            // condition instead. It belongs to whatever writes through here.
            emit("  -- VERIFY " + node.verifyText +
                 " (a store-time condition, not a view predicate)");
        }
    }

    /** One remap entry as SELECT items. A remap entry names an item of the
     *  record it redescribes, unless it is virtual or a regrouping. */
    std::vector<std::string> viewColumns(const Node& entry, const Table& table,
                                         const std::string& remap) {
        const std::string& kind = entry.kind;
        if (kind == "set" || kind == "subset" || kind == "access" ||
            kind == "remap" || kind == "dataset" || kind == "format" ||
            kind == "filler")
            return {};
        if (entry.hidden) return {};
        const std::string source = entry.renamedFrom.empty() ? entry.name : entry.renamedFrom;
        // Carried over by name: a way into the record, not data.
        if (table.structures.count(toUpper(source))) return {};
        if ((entry.type == "group" || entry.type == "field") && !entry.children.empty()) {
            // A group regrouped, or a field whose bits are renamed: what the
            // remap gives a new name to are the leaves, which are columns of
            // the table whatever the remap calls the thing above them.
            std::vector<std::string> out;
            for (const auto& child : entry.children) {
                std::vector<std::string> part = viewColumns(*child, table, remap);
                out.insert(out.end(), part.begin(), part.end());
            }
            return out;
        }
        if (entry.isVirtual) {
            if (entry.virtualExpr.empty()) {
                // Declared in the remap and computed nowhere: the work area
                // holds it for the life of the transaction, and a view has no
                // such place to keep it.
                return {"NULL AS " + quoted(sqlname(entry.name))};
            }
            std::optional<std::string> translated = translate(entry.virtualExpr, &table);
            if (!translated) {
                unsupported("remap " + remap + ": virtual " + entry.name + " = " +
                            entry.virtualExpr + " does not translate");
                return {};
            }
            return {"(" + *translated + ") AS " + quoted(sqlname(entry.name))};
        }
        std::vector<const Column*> hits = table.find(source);
        if (hits.empty()) {
            unsupported("remap " + remap + ": " + source + " is not an item of " +
                        (table.node ? table.node->name : std::string("the global items")));
            return {};
        }
        if (hits.size() == 1 && hits[0]->dasdlName() == toUpper(source)) {
            const Column& column = *hits[0];
            if (sqlname(entry.name) == column.name) return {quoted(column.name)};
            return {quoted(column.name) + " AS " + quoted(sqlname(entry.name))};
        }
        std::vector<std::string> out;
        for (const Column* col : hits) out.push_back(quoted(col->name));
        return out;
    }

    // ---- logical databases ------------------------------------------------

    void emitLogicalDatabases() {
        std::vector<const Node*> ldbs;
        for (const auto& node : db_.nodes)
            if (node->kind == "logical-database") ldbs.push_back(node.get());
        if (ldbs.empty()) return;
        emit("-- Logical databases. Which structures a program may see is");
        emit("-- a matter of grants rather than of shape, so what each one");
        emit("-- names is written out here for whoever issues them.");
        for (const Node* ldb : ldbs) {
            emit("--   " + ldb->name + ":");
            for (const auto& entry : ldb->children) {
                const std::string shown =
                    entry->name + (entry->renamedFrom.empty() ? ""
                                                              : " = " + entry->renamedFrom);
                if (entry->setsMode == "LIST") {
                    std::vector<std::string> sets;
                    for (const auto& s : entry->children)
                        sets.push_back(s->name + (s->renamedFrom.empty()
                                                      ? ""
                                                      : " = " + s->renamedFrom));
                    emit("--     " + shown + " through " + join(sets, ", "));
                } else if (!entry->setsMode.empty()) {
                    emit("--     " + shown + " through " + toLower(entry->setsMode) +
                         " of its sets");
                } else {
                    emit("--     " + shown);
                }
            }
            if (!ldb->guardFile.empty())
                emit("--     guarded by " + ldb->guardFile);
        }
        emit();
    }

    // ---- state ------------------------------------------------------------

    const Database& db_;
    Maintenance maintenance_;
    // A deque, not a vector: every Table is pointed at — by its embedded
    // children, by the name maps, by the access paths — and a vector would move
    // them out from under those pointers as it grew.
    std::deque<Table> tables_;
    std::vector<Table*> dataSets_;                  // in declaration order
    std::map<const Node*, const Table*> byNode_;
    std::map<std::string, const Table*> byName_;
    std::vector<const Node*> globals_;              // top-level items
    const Table* globalsTable_ = nullptr;
    // Every table and view name issued, so a collision is reported rather than
    // left for the server to refuse. DASDL names are unique among structures,
    // but an embedded data set's table takes its owner's name as a prefix, and
    // that prefixed name is one a top-level structure could also have.
    std::map<std::string, std::string> issued_;
    std::vector<std::string> out_;
    int unsupported_ = 0;
};

/** Write the schema for `db` to `os`. */
inline int write(std::ostream& os, const Database& db,
                 Maintenance maintenance = Maintenance::Triggers) {
    SchemaWriter writer(db, maintenance);
    writer.write(os);
    return writer.unsupportedCount();
}

}  // namespace dasdl_sql
