// Auto-generated by Trackway. Do not edit.
#pragma once

// Token type declarations (definitions are in the generated workfile).
extern const unsigned char BADTOK;
extern const unsigned char IDNTOK;
extern const unsigned char RESTOK;
extern const unsigned char NUMTOK;
extern const unsigned char INTTOK;
extern const unsigned char STRTOK;
extern const unsigned char CHRTOK;
extern const unsigned char TXTTOK;
extern const unsigned char ETXTOK;

