#!/usr/bin/env python3
"""Regenerate web/fonts.css: the latin subset of IBM Plex as data: URIs.

The page promises it fetches nothing, and a webfont link would make that false,
so the faces are embedded. Run this only to update them; the result is tracked,
and the build itself needs no network.

IBM Plex is Copyright IBM Corp., under the SIL Open Font License 1.1, which
allows the embedding this does.
"""
import base64
import os
import re
import sys
import urllib.request

URL = ('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500'
       '&family=IBM+Plex+Sans:wght@400;600&family=IBM+Plex+Serif:wght@600&display=swap')
# Google serves woff2 only to a browser-shaped caller.
UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/152.0 Safari/537.36')
HEADER = """/* IBM Plex Sans, Serif and Mono - Copyright IBM Corp., SIL Open Font License 1.1.
   Embedded as data: URIs so the page fetches nothing at all. Generated by
   web/fonts-fetch.py from the Google Fonts latin subset; do not hand-edit. */"""


def main(out):
    req = urllib.request.Request(URL, headers={'User-Agent': UA})
    css = urllib.request.urlopen(req, timeout=60).read().decode('utf-8')

    blocks = re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    latin = [b for name, b in blocks if name == 'latin']
    if not latin:
        sys.exit('fonts-fetch: no latin faces in the stylesheet')

    seen, lines, total = {}, [HEADER], 0
    for block in latin:
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        if url not in seen:
            data = urllib.request.urlopen(url, timeout=60).read()
            seen[url] = base64.b64encode(data).decode('ascii')
            total += len(data)
        inlined = re.sub(r'url\(https://[^)]+\)',
                         'url(data:font/woff2;base64,' + seen[url] + ')', block)
        lines.append(re.sub(r'\n\s*', ' ', inlined).strip())

    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print('fonts-fetch: %d faces, %d files, %.0f KB of woff2' % (len(latin), len(seen), total / 1024))


if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, 'fonts.css'))
